In [2]:
#image segmented from orginal to grayscale and binary

#Scale image as grayscale to reduce the amount of RGB pixelation required for segregation
import cv2 as cv
import numpy as np

img1 = cv.imread('Cars.jpg') #default photo
img2 = cv.imread('Cars.jpg', 0)    # synchronize dimension

#show photo dimension size
print(img1.shape)
print(img2.shape)

#resize photo
img1 = cv.resize(img1, (0,0), None, 0.2, 0.2)
img2 = cv.resize(img2, (0,0), None, 0.2, 0.2)

#convert to grayscale
img2 = cv.cvtColor(img2, cv.COLOR_GRAY2BGR)

#Finding edges on images
img3=cv.Canny(img2, 30, 200)

#use a copy of your image, e.g. - edged.copy(), since finding contours alter the image
#we have to add _, before the contours as an empty argument due to upgrade of the OpenCV version
_, contours=cv.findContours(img3,cv.RETR_EXTERNAL,cv.CHAIN_APPROX_NONE)

#print contour
print(contours)
print('Numbers of contours found=' + str(len(contours)))

#output
cv.imshow('Orignal_Cars', img1)
cv.imshow('Grayscale_Cars', img2)
cv.imshow('Binary_Cars', img3)

cv.imwrite('Orignal_Cars.jpg', img1)
cv.imwrite('Grayscale_Cars.jpg', img2)
cv.imwrite('Binary_Cars.jpg', img3)

cv.waitKey(0)
cv.destroyAllWindows()

(988, 1023, 3)
(988, 1023)
[[[ 1 -1 -1 -1]
  [ 2  0 -1 -1]
  [ 3  1 -1 -1]
  [ 4  2 -1 -1]
  [ 5  3 -1 -1]
  [ 6  4 -1 -1]
  [ 7  5 -1 -1]
  [ 8  6 -1 -1]
  [ 9  7 -1 -1]
  [10  8 -1 -1]
  [11  9 -1 -1]
  [12 10 -1 -1]
  [13 11 -1 -1]
  [14 12 -1 -1]
  [15 13 -1 -1]
  [16 14 -1 -1]
  [17 15 -1 -1]
  [18 16 -1 -1]
  [19 17 -1 -1]
  [20 18 -1 -1]
  [-1 19 -1 -1]]]
Numbers of contours found=1


In [ ]:
#test prototype

#Scale image as grayscale to reduce the amount of RGB pixelation required for segregation
import cv2 as cv
import numpy as np

car_cascade = cv.CascadeClassifier('cars.xml')  #Path to cars.xml

img1 = cv.imread('R.jpg') #default photo
img2 = cv.imread('R.jpg', 0)    # synchronize dimension

#show photo dimension size
print(img1.shape)
print(img2.shape)

#resize photo
img1 = cv.resize(img1, (0,0), None, 0.5, 0.5)
img2 = cv.resize(img2, (0,0), None, 0.5, 0.5)

#convert to grayscale
img2 = cv.cvtColor(img2, cv.COLOR_GRAY2BGR)

#Finding edges on images
img3=cv.Canny(img2, 30, 200)

#use a copy of your image, e.g. - edged.copy(), since finding contours alter the image
#we have to add _, before the contours as an empty argument due to upgrade of the OpenCV version
_, contours=cv.findContours(img3,cv.RETR_EXTERNAL,cv.CHAIN_APPROX_NONE)

#print contour
print(contours)
print('Numbers of contours found=' + str(len(contours)))

cars=car_cascade.detectMultiScale(img3,1.8,2)

#Drawing rectangles on detected cars
for (x,y,w,h) in cars:
    cv.rectangle(img3,(x,y),(x+w,y+h),(225,0,0),2)

#output
cv.imshow('R', img1)
cv.imshow('Grayscale_R', img2)
cv.imshow('SurprisedVR', img3)
cv.imshow('cars', cars)

cv.waitKey(0)
cv.destroyAllWindows()